### ISSUE TITLE
Theory Section For Collision

### ISSUE THREAD

**Issue by brtymn** [ThePhysHub/ThePhysicsHub#13]
# Theory Section For Collision Simulation

The theory section for the collision simulation is needed. 

## Type of issue

- [ ] New Feature
- [ ] Bug
- [x] Documentation

## Possible Fixes / Implementations

The theory section needs to be written with university level physics.

**Comment by Sudheer121** [comment]
I can work on adding collision explanation using vectors in 2 dimensions. Assign me this .

**Comment by Sudheer121** [comment]
Will text and math equations be ok ?. Or svgs are also needed just like the theory section in n-body simulation.

**Comment by 20akshay00** [comment]
The SVGs were an experiment.. so not completely necessary but innovation is encouraged as we're still finding fun ways to present the theory. You can do the text and equations for now, that's fine.

**Comment by Sudheer121** [comment]
Assign me this, working on this.
