### ISSUE TITLE
Issue From A Reddit User - Web Dev

### ISSUE THREAD

**Issue by brtymn** [ThePhysHub/ThePhysicsHub#30]
# Github and Patreon Logos

The comment by the redditor: Heads-up: you might want to tweak your markup on the https://physicshub.herokuapp.com/contribute page - I found that the logo images were being blocked by my ad blocker.

Realistically, the text for "GitHub" and "Patreon" could just as easily be linked - when I couldn't see the logos, I moused over the text and was bemused that neither word was hyperlinked. My $0.02 though...

## Type of issue

- [ ] New Feature
- [x] Bug
- [ ] Documentation

**Comment by justusmattern** [comment]
done
